name: tomtom_flutter_map_example
description: Demonstrates how to use the tomtom_flutter_map plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  tomtom_flutter_map: ^0.1.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
